import r1 from "@/assets/recipe-1.jpg";
import r2 from "@/assets/recipe-2.jpg";
import r3 from "@/assets/recipe-3.jpg";
import r4 from "@/assets/recipe-4.jpg";

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function getTrendingRecipes(count = 4): Recipe[] {
  return shuffle(trendingRecipes).slice(0, count);
}

export type Recipe = {
  id: string;
  title: string;
  time: string;
  difficulty: string;
  tag: string;
  image: string;
  calories: number;
  servings: number;
  ingredients: string[];
  steps: string[];
};

export const trendingRecipes: Recipe[] = [
  {
    id: "1",
    title: "Garden Veggie Stir-Fry",
    time: "20 min",
    difficulty: "Easy",
    tag: "Vegan",
    image: r1,
    calories: 320,
    servings: 2,
    ingredients: [
      "2 tbsp sesame oil",
      "1 red bell pepper, sliced",
      "1 courgette, sliced",
      "100g broccoli florets",
      "2 cloves garlic, minced",
      "1 tbsp soy sauce",
      "1 tsp fresh ginger, grated",
      "1 tsp cornflour",
      "Sesame seeds to garnish",
    ],
    steps: [
      "Heat sesame oil in a wok over high heat.",
      "Add garlic and ginger, stir-fry for 30 seconds.",
      "Add broccoli and stir-fry for 2 minutes.",
      "Add bell pepper and courgette, cook for 3 more minutes.",
      "Mix soy sauce with cornflour and a splash of water, pour over veg.",
      "Toss everything together until the sauce thickens.",
      "Serve immediately, garnished with sesame seeds.",
    ],
  },
  {
    id: "2",
    title: "Creamy Avocado Pasta",
    time: "15 min",
    difficulty: "Easy",
    tag: "Quick",
    image: r2,
    calories: 490,
    servings: 2,
    ingredients: [
      "200g pasta (linguine or spaghetti)",
      "2 ripe avocados",
      "2 cloves garlic",
      "Juice of 1 lemon",
      "2 tbsp olive oil",
      "Small bunch fresh basil",
      "Salt and black pepper",
      "Chilli flakes (optional)",
    ],
    steps: [
      "Cook pasta according to packet instructions. Reserve ½ cup pasta water.",
      "Blend avocados, garlic, lemon juice, olive oil and basil until smooth.",
      "Season with salt and pepper.",
      "Drain pasta and toss with the avocado sauce, adding pasta water to loosen.",
      "Serve immediately with chilli flakes if desired.",
    ],
  },
  {
    id: "3",
    title: "Green Power Smoothie Bowl",
    time: "10 min",
    difficulty: "Easy",
    tag: "Healthy",
    image: r3,
    calories: 280,
    servings: 1,
    ingredients: [
      "1 frozen banana",
      "1 cup frozen mango chunks",
      "2 handfuls baby spinach",
      "120ml coconut milk",
      "Toppings: granola, kiwi slices, chia seeds, honey",
    ],
    steps: [
      "Blend banana, mango, spinach and coconut milk until completely smooth.",
      "Pour into a bowl — the mixture should be thick, not pourable.",
      "Add toppings: granola, fresh kiwi, chia seeds and a drizzle of honey.",
      "Serve immediately.",
    ],
  },
  {
    id: "4",
    title: "Herb Grilled Chicken",
    time: "30 min",
    difficulty: "Medium",
    tag: "Protein",
    image: r4,
    calories: 410,
    servings: 2,
    ingredients: [
      "2 chicken breasts",
      "2 tbsp olive oil",
      "2 cloves garlic, crushed",
      "1 tsp dried oregano",
      "1 tsp smoked paprika",
      "½ tsp dried thyme",
      "Juice of ½ lemon",
      "Salt and black pepper",
    ],
    steps: [
      "Mix olive oil, garlic, oregano, paprika, thyme, lemon juice, salt and pepper.",
      "Score the chicken breasts and coat thoroughly in the marinade.",
      "Leave to marinate for at least 10 minutes (or overnight in the fridge).",
      "Heat a griddle pan over high heat. Cook chicken 6–7 minutes per side.",
      "Rest for 5 minutes before slicing and serving.",
    ],
  },
  {
    id: "5",
    title: "Spicy Lentil Soup",
    time: "25 min",
    difficulty: "Easy",
    tag: "Vegan",
    image: r1,
    calories: 290,
    servings: 3,
    ingredients: [
      "200g red lentils",
      "1 onion, diced",
      "2 cloves garlic",
      "1 tsp cumin",
      "1 tsp smoked paprika",
      "½ tsp chilli flakes",
      "400ml vegetable stock",
      "1 tin chopped tomatoes",
      "Juice of ½ lemon",
    ],
    steps: [
      "Soften onion and garlic in a little oil over medium heat.",
      "Add cumin, paprika and chilli flakes, cook 1 minute.",
      "Add lentils, tomatoes and stock. Bring to a boil.",
      "Simmer 20 minutes until lentils are soft.",
      "Squeeze in lemon juice and season. Blend partially if desired.",
    ],
  },
  {
    id: "6",
    title: "Banana Oat Pancakes",
    time: "15 min",
    difficulty: "Easy",
    tag: "Healthy",
    image: r3,
    calories: 340,
    servings: 2,
    ingredients: [
      "2 ripe bananas",
      "2 eggs",
      "80g rolled oats",
      "½ tsp baking powder",
      "Pinch of cinnamon",
      "Coconut oil for frying",
      "Toppings: berries, maple syrup",
    ],
    steps: [
      "Blend bananas, eggs, oats, baking powder and cinnamon until smooth.",
      "Heat coconut oil in a non-stick pan over medium heat.",
      "Pour small rounds of batter and cook 2 minutes per side.",
      "Serve with fresh berries and a drizzle of maple syrup.",
    ],
  },
  {
    id: "7",
    title: "Garlic Butter Salmon",
    time: "20 min",
    difficulty: "Medium",
    tag: "Protein",
    image: r4,
    calories: 460,
    servings: 2,
    ingredients: [
      "2 salmon fillets",
      "3 tbsp butter",
      "4 cloves garlic, minced",
      "Juice of 1 lemon",
      "1 tbsp fresh dill or parsley",
      "Salt and pepper",
      "Steamed greens to serve",
    ],
    steps: [
      "Season salmon with salt and pepper.",
      "Melt butter in a pan over medium-high heat.",
      "Cook salmon skin-side up for 4 minutes, flip and cook 3 more.",
      "Add garlic to the pan and cook 1 minute until fragrant.",
      "Pour over lemon juice and herbs. Serve with greens.",
    ],
  },
  {
    id: "8",
    title: "Chickpea Tikka Masala",
    time: "30 min",
    difficulty: "Medium",
    tag: "Vegan",
    image: r2,
    calories: 380,
    servings: 3,
    ingredients: [
      "2 tins chickpeas, drained",
      "1 onion, diced",
      "3 cloves garlic",
      "1 tbsp fresh ginger",
      "3 tbsp tikka masala paste",
      "400ml coconut milk",
      "1 tin chopped tomatoes",
      "Fresh coriander to serve",
      "Basmati rice to serve",
    ],
    steps: [
      "Fry onion, garlic and ginger in oil until softened.",
      "Add tikka masala paste and cook 2 minutes.",
      "Add tomatoes and coconut milk, stir well.",
      "Add chickpeas and simmer 20 minutes until sauce thickens.",
      "Serve over basmati rice with fresh coriander.",
    ],
  },
  {
    id: "9",
    title: "Turkish Eggs (Çilbir)",
    time: "15 min",
    difficulty: "Easy",
    tag: "Quick",
    image: r3,
    calories: 310,
    servings: 2,
    ingredients: [
      "4 eggs",
      "200g Greek yoghurt",
      "2 cloves garlic, grated",
      "3 tbsp butter",
      "1 tsp smoked paprika",
      "½ tsp chilli flakes",
      "Fresh dill",
      "Crusty bread to serve",
    ],
    steps: [
      "Mix yoghurt with garlic and season well. Spread into bowls.",
      "Poach eggs in gently simmering water for 3 minutes.",
      "Melt butter in a pan, add paprika and chilli flakes.",
      "Place eggs on yoghurt, drizzle over the spiced butter.",
      "Top with dill and serve with crusty bread.",
    ],
  },
  {
    id: "10",
    title: "Mango Coconut Chia Pudding",
    time: "10 min",
    difficulty: "Easy",
    tag: "Healthy",
    image: r3,
    calories: 240,
    servings: 2,
    ingredients: [
      "6 tbsp chia seeds",
      "400ml coconut milk",
      "1 tbsp maple syrup",
      "1 ripe mango, diced",
      "Toasted coconut flakes",
      "Lime zest",
    ],
    steps: [
      "Mix chia seeds, coconut milk and maple syrup together.",
      "Refrigerate for at least 4 hours or overnight.",
      "Stir well before serving.",
      "Top with mango, coconut flakes and lime zest.",
    ],
  },
  {
    id: "11",
    title: "One-Pan Shakshuka",
    time: "25 min",
    difficulty: "Easy",
    tag: "Quick",
    image: r1,
    calories: 290,
    servings: 2,
    ingredients: [
      "1 onion, diced",
      "1 red pepper, sliced",
      "2 cloves garlic",
      "1 tsp cumin",
      "1 tsp paprika",
      "1 tin chopped tomatoes",
      "4 eggs",
      "Fresh parsley",
      "Crusty bread",
    ],
    steps: [
      "Fry onion, pepper and garlic in oil until soft.",
      "Add spices and cook 1 minute.",
      "Pour in tomatoes, season and simmer 10 minutes.",
      "Make wells in the sauce and crack in the eggs.",
      "Cover and cook until whites are set but yolks still runny.",
      "Scatter parsley and serve straight from the pan.",
    ],
  },
  {
    id: "12",
    title: "Prawn Stir-Fry Noodles",
    time: "15 min",
    difficulty: "Easy",
    tag: "Protein",
    image: r4,
    calories: 420,
    servings: 2,
    ingredients: [
      "200g egg noodles",
      "250g cooked king prawns",
      "2 cloves garlic",
      "1 tbsp sesame oil",
      "2 tbsp soy sauce",
      "1 tbsp oyster sauce",
      "Spring onions",
      "Beansprouts",
      "Red chilli, sliced",
    ],
    steps: [
      "Cook noodles per packet. Drain and set aside.",
      "Heat sesame oil in a wok over high heat.",
      "Fry garlic 30 seconds, add prawns and toss.",
      "Add noodles, soy sauce and oyster sauce. Toss everything.",
      "Add beansprouts, toss 1 minute.",
      "Serve topped with spring onions and chilli.",
    ],
  },
];
